# Generated by Django 5.2 on 2025-04-26 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlcoholProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название продукта')),
                ('brand', models.CharField(max_length=100, verbose_name='Бренд')),
                ('category', models.CharField(choices=[('beer', 'Пиво'), ('wine', 'Вино'), ('spirit', 'Крепкий алкоголь')], default='beer', max_length=10, verbose_name='Категория')),
                ('volume_ml', models.PositiveIntegerField(verbose_name='Объем (мл)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена, RUB')),
                ('in_stock', models.BooleanField(default=True, verbose_name='В наличии')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
        ),
    ]
