# Generated by Django 5.2 on 2025-05-10 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alcoholproduct',
            name='supplier',
            field=models.CharField(blank=True, max_length=100, verbose_name='Поставщик'),
        ),
    ]
