#version: '3.8'

services:
  postgres_service:
    image: postgres:17-alpine
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${PGDATABASE}
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend_service:
    build: #образ
      context: ./backend
      dockerfile: Dockerfile
    depends_on: 
      - postgres_service
    env_file:
      - .env
    environment:
      DATABASE_NAME: ${PGDATABASE}
      DATABASE_USER: ${PGUSER}
      DATABASE_PASSWORD: ${PGPASSWORD}
      DATABASE_HOST: postgres_service
      DATABASE_PORT: ${PGPORT}
    volumes:
      - static_volume:/staticfiles
    expose:
      - "8000"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PGUSER} -d ${PGDATABASE}"]
      interval: 5s
      timeout: 5s
      retries: 5      

  nginx_service:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    depends_on:
      - backend_service
    ports:
      - "80:80"
    volumes:
      - static_volume:/staticfiles

volumes:
  postgres_data:
  static_volume:
